### PR TITLE
feat: Added support for NAT44 static mapping twice-NAT pool IP address reference

### PR DESCRIPTION
**Pull request by fgschwan**
This is new functionality in VPP 20.09.

### CODE REVIEW

**Comment by rastislavszabo** [comment]
Hi, what is still WIP in this PR? Can it be merged?

**Review by rastislavszabo — DISMISSED** [review]

**Comment by fgschwan** [comment]
> Hi, what is still WIP in this PR? Can it be merged?
Hi, it is still missing dependecies and error messages.

**Review by rastislavszabo — APPROVED** [review]

**Comment by ondrej-fabry** [comment]
Planning to add any integration or end-to-end tests?

**Comment by fgschwan** [comment]
@ondrej-fabry Added simple integration tests https://github.com/ligato/vpp-agent/pull/1728/commits/1fad79add2075d249733c72e3a99ca57b906200e 
I basically started with this the NAT integration testing, so i added also some super basic NAT tests that convert to the test testing this PR functionality.

**Review by rastislavszabo — APPROVED** [review]

**Review by ondrej-fabry — APPROVED** [review]

**Pull request merged**
