### PR TITLE
Add srv6 configuration to ConfiguratorClient model

### PR DESCRIPTION
**Pull request by artem-belov**
Signed-off-by: Artem Belov <artem.belov@xored.com>

### CODE REVIEW

**Comment by artem-belov** [comment]
@ondrej-fabry Hello.
I was trying to configure SRv6 via GenericManagerClient but was blocked with missing ability to remove configuration because Delete function doesn't have difference with Update:
https://github.com/ligato/vpp-agent/blob/2c193f25dad12a63c2d2bea862556c150b7af359/client/remoteclient/grpc_client.go#L133-L165

It would be very helpful if you will apply this patch for us and update release
Thank you

**Comment by edwarnicke** [comment]
@artem-belov See #1441

**Comment by ondrej-fabry** [comment]
> @artem-belov See #1441

I made new PR with `dev` branch as base and included another missing config for recently added VPP feature: SPAN.

**Comment by ondrej-fabry** [comment]
Closing in favor of #1441

**Pull request closed without merging**
