### PR TITLE
Add new python proto parsers

### PR DESCRIPTION
**Pull request by miroslavKovacPantheon**
Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>

### CODE REVIEW

**Comment by ondrej-fabry** [comment]
Is this still work in progress?

**Comment by miroslavKovacPantheon** [comment]
> 
> 
> @miroslavKovacPantheon Is this still work in progress?

@ondrej-fabry sorry.. It s ready now.

**Comment by ondrej-fabry** [comment]
Why was the mode for file `scripts/check_links.sh` changed to non-executable?

**Comment by miroslavKovacPantheon** [comment]
> 
> 
> Why the change of mode for file `scripts/check_links.sh` to non-executable?

Sorry. No idea why it changed. I didn t relized it got pushed there. It s fixed now.

Nice catch btw. thx.

**Pull request merged**
