### PR TITLE
improvement: Expose GoVPP stats in govppmux API

### PR DESCRIPTION
**Pull request by rastislavszabo**
Signed-off-by: Rastislav Szabo <raszabo@cisco.com>

### CODE REVIEW

**Comment by ondrej-fabry** [comment]
@rastislavszabo I'm not sure putting statistics/metrics as part of govppmux plugin (or any other plugin) API is a proper solution, especially because the stats are global and not coupled with the plugin. 

Could you help clarify the reasoning behind this change? There already was exported function `GetStats()` for retrieving the stats data.

**Comment by rastislavszabo** [comment]
@ondrej-fabry The idea was to expose govppp binary api counters/stats to make them consumable programmatically, not only via REST. These are coupled with the govppmux plugin, Would be exposing everything except `govppmux.Metrics` more acceptable to you? E.g.:
```go
type BinAPIStats struct {
	Errors      metrics.Calls
	AllMessages metrics.CallStats
	Messages    metrics.Calls
	Replies     metrics.Calls
}
```

Or is it not acceptable at all?

**Comment by ondrej-fabry** [comment]
I was not referring to retrieving stats via REST. You can access the govppmux stats programmatically with the current implementation already, using the exported function `GetStats()`. This PR only adds a new method for Plugin that calls `GetStats()` and returns just it, which in essence does not make much sense since it's global data.

**Comment by rastislavszabo** [comment]
right, OK it's not really needed to have in included in API

**Pull request closed without merging**
