### PR TITLE
Model + descriptor for VRF table

### PR DESCRIPTION
**Pull request by milanlenco**
TODO:
- [x] code cleanup
- [x] testing with all supported VPP versions
- [x] testing with Contiv

### CODE REVIEW

**Comment by ondrej-fabry** [comment]
@milanlenco how far along are you with this? The PR #1278 is ready. 

Perhaps it might be better to split unrelated changes next time.. because this PR now contains new feature (VRF model) + large refactor (descriptor constructors).

**Comment by milanlenco** [comment]
OK, lets merge #1278 first...

Yeah the cleanup could have been separate, but actually the complication here are the changes done in vppcalls for VRFs, but I will propagate them to 19.04...

**Comment by ondrej-fabry** [comment]
Waiting for reply from @milanlenco before merging..

**Comment by milanlenco** [comment]
I have tested these changes against the latest Contiv from the dev branch.
First I pulled the latest changes from dev into my local repo, then modified Gopkg.toml:
```
--- a/Gopkg.toml
+++ b/Gopkg.toml
@@ -44,7 +44,9 @@ required = [
 
 [[constraint]]
   name = "github.com/ligato/vpp-agent"
-  version = "2.0.1"
+  branch = "vrf"
+  source = "github.com/milanlenco/vpp-agent"
+  #version = "2.0.1"
```
and finally run `dep ensure -v` to get the updates into the vendor directory.
Did you also use the `dep` tool, or have you copied the agent manually into the vendor?

**Comment by ondrej-fabry** [comment]
```
../../../../ligato/vpp-agent-generic/pkg/models/encoding.go:103:4: cannot use any (type *"github.com/ligato/vpp-agent-generic/vendor/github.com/gogo/protobuf/types".Any) as type *"github.com/ligato/vpp-agent/vendor/github.com/gogo/protobuf/types".Any in field value
```

WHere does the part `vpp-agent-generic` come from? Some mismatch of two types.. for some reason goimports imported wrong vpp-agent directory?

**Comment by fgschwan** [comment]
Sorry, mistake on my end (used import for renamed vpp-agent sitting in my gopath, that was the vpp-agent-generic). Everything is ok.

**Comment by ondrej-fabry** [comment]
Merging.

**Pull request merged**
